version: "3"

services:
  mysql-master:
    image: mysql:8.0
    container_name: proxysql-mysql-replication-master
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: test
      MYSQL_PASSWORD: pass
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
      - .data:/var/lib/mysql
    ports:
      - 3308:3306
  proxysql:
    image: proxysql/proxysql:2.0.12
    container_name: proxysql-mysql-replication-proxysql
    ports:
      - 6032:6032
      - 6033:6033
    volumes:
      - ./proxysql/proxysql.cnf:/etc/proxysql.cnf
    depends_on:
      - mysql-master