version: "3"

services:
  mysql-master:
    image: mysql:8.0
    container_name: proxysql-mysql-replication-master
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: test
      MYSQL_PASSWORD: pass
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
      - .data:/var/lib/mysql
      - ./binlog:/var/log/mysql
    ports:
      - 3308:3306
  proxysql:
    #platform: linux/x86_64
    build:
      context: .
      dockerfile: ./proxysql/Dockerfile
    container_name: proxysql-mysql
    environment:
      PROXY_USER: root
      PROXY_PASSWORD: rootpass
    ports:
      - 6032:6032
      - 6033:6033
      - 6080:6080
    entrypoint: >
      /bin/sh -c "envsubst < /etc/proxysql.cnf.template > /etc/proxysql.cnf && proxysql -f --idle-threads -D /var/lib/proxysql"
    volumes:
      - ./proxysql/proxysql.cnf.template:/etc/proxysql.cnf.template
    depends_on:
      - mysql-master